# Use the official NGINX image from the Docker Hub
FROM nginx:latest

# Copy the custom HTML file to the appropriate location in the NGINX container
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to the outside world
EXPOSE 80
